version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - ./certs/privkey.pem:/etc/ssl/private/privkey.pem
      - ./web_files:/usr/share/nginx/html
    depends_on:
      - chatdocument_app

  chatdocument_app:
    build:
      context: ./chatdocument_app
    image: image_chatdocument_app:latest  # Define el nombre explícitamente
    container_name: chatdocument_app
    ports:
      - "8501:8501"