version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      #- ./nginx.conf:/etc/nginx/conf.d/default.conf
      #- ./certs/fullchain.pem:/etc/ssl/certs/fullchain.pem
      #- ./certs/privkey.pem:/etc/ssl/private/privkey.pem
      #- ./app_enriquevicenteh:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs/enrique.vicenteh.com/fullchain.pem:/etc/ssl/certs/enrique.vicenteh.com.pem
      - ./certs/enrique.vicenteh.com/privkey.pem:/etc/ssl/private/enrique.vicenteh.com.pem
      - ./certs/vivelunahuana.com/fullchain.pem:/etc/ssl/certs/vivelunahuana.com.pem
      - ./certs/vivelunahuana.com/privkey.pem:/etc/ssl/private/vivelunahuana.com.pem
      - ./app_enriquevicenteh:/usr/share/nginx/html      
    depends_on:
      - chatdocument_app
      - wordpress

  chatdocument_app:
    build:
      context: ./chatdocument_app
    image: image_chatdocument_app:latest  # Define el nombre explícitamente
    container_name: chatdocument_app
    ports:
      - "8501:8501"

  wordpress:
    build:
      context: ./wordpress_app
    container_name: wordpress_app
    ports:
      - "8080:80"
    environment:
      - DB_NAME=${WORDPRESS_DB_NAME}
      - DB_USER=${WORDPRESS_DB_USER}
      - DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - DB_HOST=${WORDPRESS_DB_HOST}
    volumes:
      - ./wordpress/wp-content:/var/www/html/wp-content

volumes:
  db_data: {}