version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - ./certs/privkey.pem:/etc/ssl/private/privkey.pem
      - ./app_enriquevicenteh:/usr/share/nginx/html
    depends_on:
      - chatdocument_app
    #depends_on:
    #  chatdocument_app:
    #    condition: service_healthy

  chatdocument_app:
    build:
      context: ./chatdocument_app
    image: image_chatdocument_app:latest  # Define el nombre explícitamente
    container_name: chatdocument_app
    ports:
      - "8501:8501"
#    healthcheck:
#      test: ["CMD-SHELL", "curl -f http://172.26.0.2:8501/ || exit 1"]
#      interval: 30s
#      timeout: 10s
#      retries: 5